### ISSUE TITLE
Opera

### ISSUE THREAD

**Issue by ys-chung** [jkingsman/bishop#17]
Opera is based on Chromium for quite a while now, and other projects such as uBlock supports Opera while supporting Chrome/Chromium. Is bishop for Opera feasible?

**Comment by jkingsman** [comment]
I'll look into that.

**Comment by jkingsman** [comment]
So it looks like enabling Developer Mode and then importing the `dist` folder works passably. I get an error on the Extensions screen about a security policy violation and it refusing to run a script, but it all seems to run fine so I'm going to call that an inconsequential bug while I chase it down.

My answer is yes, it works with (probably) ignorable errors. The error issue is now #18.
